model:
  name: "facebook/nllb-200-3.3B"
  device: "cuda"
  dtype: "float16" # Full Precision for A40

dataset:
  hf_dataset: "amaniopia/merged_train"
  hf_split: "train"
  max_rows: null 

paths:
  output_dir: "./distilled_data"

huggingface:
  token: ""
  username: ""
  repo_name: "nllb-distilled-dataset-v1" 
  private: true

translation:
  batch_size: 32
  num_beams: 3
  max_length: 512
  chunk_size: 500

filtering:
  qe_model: "masakhane/africomet-qe-stl-1.1"
  qe_threshold: 0.60     # Minimum Score. If lower, translation is set to None.
  min_len_ratio: 0.25    # If translation is too short/long, set to None.
  max_len_ratio: 4.0
  batch_size: 64

language_pairs:
 
  - ["en", "am"]

  - ["zu", "en"]
  
  - ["en", "so"]

  - ["yo", "en"]
  
  - ["en", "wo"]
  
  - ["wo", "fr"]
  
  - ["fr", "ln"]
